---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    - ['private_network', {type: 'dhcp'}]

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[maitred]
