---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    - ['private_network', {type: 'dhcp'}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[maitred]
    verifier:
      inspec_tests:
        - test/smoke/default
