language: ruby

install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle install --without=development integration

script:
  - chef exec bundle exec rake && chef exec bundle exec kitchen test

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
